### ISSUE TITLE
[SECURITY] Input Validation

### ISSUE THREAD

**Issue by Oguzoz1** [Oguzoz1/FluxTalk#11]
### Description

We need to enhance the security of our application by implementing input validation for all user inputs and data processed by the server. This will help protect against common vulnerabilities such as injection attacks, buffer overflows, and ensure that only valid and safe data is processed.

### Tasks

- [ ] **Define Valid Input**: 
  - Specify expected data types (e.g., integer, string, email address).
  - Set limits on acceptable range or length of input values (e.g., usernames must be between 3 and 15 characters).

- [ ] **Implement Input Validation**:
  - **For Text Input**:
    - Check length and format of inputs (e.g., username length validation).
    - Sanitize inputs to remove or escape special characters.
  - **For Numeric Input**:
    - Validate range (e.g., port numbers should be between 1 and 65535).
    - Parse and validate numeric inputs properly.

- [ ] **Use Libraries or Frameworks**:
  - Integrate validation libraries where applicable (e.g., `FluentValidation` for C#).

- [ ] **Testing and Reviewing**:
  - Write unit tests to ensure validation rules are enforced.
  - Conduct code reviews to ensure comprehensive and secure validation.

### Example Implementation

**For Text Input Validation:**

```csharp
public static bool IsValidUsername(string username)
{
    return !string.IsNullOrWhiteSpace(username) && username.Length >= 3 && username.Length <= 15;
}

public static string SanitizeInput(string input)
{
    return input.Replace("<", "&lt;").Replace(">", "&gt;").Replace("&", "&amp;");
}
